/**
 * COPY-REVIEW.md is what independent reviewers read (BUILD-STANDARD point 14). It is
 * generated by tools/copy-review.ts, so it must never go stale or leave a string out:
 * nothing that produces a checked artifact lives only in a scratchpad.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { buildCopyReview, COPY_REVIEW_PATH } from "../../tools/copy-review.ts";

describe("COPY-REVIEW.md", () => {
  const built = buildCopyReview();

  it("covers every on-screen string in the app source", () => {
    assert.deepEqual(
      built.leftovers,
      [],
      `add these to tools/copy-review.ts, then run npm run copy-review:\n${built.leftovers.join("\n")}`,
    );
  });

  it("is up to date with the source (npm run copy-review regenerates it)", () => {
    const onDisk = readFileSync(COPY_REVIEW_PATH, "utf8").replace(/\r\n/g, "\n");
    assert.ok(
      onDisk === built.markdown,
      "COPY-REVIEW.md is out of date: run npm run copy-review and commit the result",
    );
  });

  it("lists something, not an empty document", () => {
    assert.ok(built.entries > 100, `only ${built.entries} entries`);
  });
});
